# Import the modules

In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Import the dataset

In [43]:
dataset = pd.read_csv("/content/drive/MyDrive/Machine Learning A - Z/Part 3 - Classification/Classification Summative Project/drug200.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# Encoding the independent variables

In [44]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,2,3])],
                      remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

le = LabelEncoder()
y = le.fit_transform(y)

In [45]:
print(X)

[[1.0 0.0 1.0 ... 0.0 23 25.355]
 [0.0 1.0 0.0 ... 0.0 47 13.093]
 [0.0 1.0 0.0 ... 0.0 47 10.114]
 ...
 [0.0 1.0 0.0 ... 0.0 52 9.894]
 [0.0 1.0 0.0 ... 1.0 23 14.02]
 [1.0 0.0 0.0 ... 1.0 40 11.349]]


# Splitting the dataset into Training and Testing sets

In [46]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

# Feature Scaling

In [47]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, -2:] = sc.fit_transform(X_train[:, -2:])
X_test[:, -2:] = sc.transform(X_test[:, -2:])

In [48]:
print(X_train)

[[0.0 1.0 0.0 ... 0.0 0.9205170833946688 -0.8603210583298981]
 [0.0 1.0 0.0 ... 1.0 -0.4276486878157828 -0.25018559563785886]
 [1.0 0.0 0.0 ... 1.0 1.5945999689998944 -0.15462711605272095]
 ...
 [1.0 0.0 0.0 ... 1.0 0.24643419778944298 -0.4732006268287422]
 [1.0 0.0 0.0 ... 1.0 -1.7145341966984866 -0.9543864366715183]
 [0.0 1.0 1.0 ... 1.0 -0.3050881631602872 -0.08485856703743534]]


# Fitting the model to the Training Set

In [49]:
from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier()

# Predicting the Test Set

In [50]:
y_pred = classifier.predict(X_test)

# Evaluating the model

In [51]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[34  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  2  3  0  0]
 [ 0  0  0  4  0]
 [ 0  0  0  0 12]]


0.9666666666666667