# Import the modules

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Import the dataset

In [9]:
dataset = pd.read_csv("/content/drive/MyDrive/Machine Learning A - Z/Part 3 - Classification/Classification Summative Project/drug200.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

# Encoding categorical independent variables

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1, 2, 3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

le = LabelEncoder()
y = le.fit_transform(y)

# Splitting the dataset into Training and Test set

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

# Feature Scaling



In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, -2:] = sc.fit_transform(X_train[:, -2:])
X_test[:, -2:] = sc.transform(X_test[:, -2:])

In [13]:
print(X_train)

[[0.0 1.0 0.0 ... 0.0 -1.2133684023182574 2.086200821147155]
 [1.0 0.0 0.0 ... 0.0 -1.1548726804434102 -0.7987215777903738]
 [1.0 0.0 1.0 ... 1.0 -1.3303598460679515 1.6682627249299353]
 ...
 [0.0 1.0 0.0 ... 1.0 0.48300753205230923 2.2553466911289766]
 [1.0 0.0 0.0 ... 0.0 -0.9208897929440217 0.45906134373302765]
 [0.0 1.0 1.0 ... 1.0 0.30752036642776787 -1.3921006168204544]]


# Fit the model with the Training set

In [14]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

# Predicting the Test set

In [15]:
y_pred = classifier.predict(X_test)

# Evaluating the model


In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[24  0  0  0  0]
 [ 0  7  3  0  0]
 [ 0  0  2  0  0]
 [ 0  0  0  4  0]
 [ 3  0  0  0 17]]


0.9