# Import the modules

In [76]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Import the dataset


In [77]:
dataset = pd.read_csv("/content/drive/MyDrive/Machine Learning A - Z/Part 3 - Classification/Classification Summative Project/drug200.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [78]:
print(X)

[[23 'F' 'HIGH' 'HIGH' 25.355]
 [47 'M' 'LOW' 'HIGH' 13.093]
 [47 'M' 'LOW' 'HIGH' 10.114]
 [28 'F' 'NORMAL' 'HIGH' 7.798]
 [61 'F' 'LOW' 'HIGH' 18.043]
 [22 'F' 'NORMAL' 'HIGH' 8.607]
 [49 'F' 'NORMAL' 'HIGH' 16.275]
 [41 'M' 'LOW' 'HIGH' 11.037]
 [60 'M' 'NORMAL' 'HIGH' 15.171]
 [43 'M' 'LOW' 'NORMAL' 19.368]
 [47 'F' 'LOW' 'HIGH' 11.767]
 [34 'F' 'HIGH' 'NORMAL' 19.199]
 [43 'M' 'LOW' 'HIGH' 15.376]
 [74 'F' 'LOW' 'HIGH' 20.942]
 [50 'F' 'NORMAL' 'HIGH' 12.703]
 [16 'F' 'HIGH' 'NORMAL' 15.516]
 [69 'M' 'LOW' 'NORMAL' 11.455]
 [43 'M' 'HIGH' 'HIGH' 13.972]
 [23 'M' 'LOW' 'HIGH' 7.298]
 [32 'F' 'HIGH' 'NORMAL' 25.974]
 [57 'M' 'LOW' 'NORMAL' 19.128]
 [63 'M' 'NORMAL' 'HIGH' 25.917]
 [47 'M' 'LOW' 'NORMAL' 30.568]
 [48 'F' 'LOW' 'HIGH' 15.036]
 [33 'F' 'LOW' 'HIGH' 33.486]
 [28 'F' 'HIGH' 'NORMAL' 18.809]
 [31 'M' 'HIGH' 'HIGH' 30.366]
 [49 'F' 'NORMAL' 'NORMAL' 9.381]
 [39 'F' 'LOW' 'NORMAL' 22.697]
 [45 'M' 'LOW' 'HIGH' 17.951]
 [18 'F' 'NORMAL' 'NORMAL' 8.75]
 [74 'M' 'HIGH' 'HIGH' 

In [79]:
print(y)

['DrugY' 'drugC' 'drugC' 'drugX' 'DrugY' 'drugX' 'DrugY' 'drugC' 'DrugY'
 'DrugY' 'drugC' 'DrugY' 'DrugY' 'DrugY' 'drugX' 'DrugY' 'drugX' 'drugA'
 'drugC' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'drugX' 'DrugY' 'DrugY' 'drugX' 'drugB' 'drugX' 'DrugY' 'drugX' 'drugX'
 'drugA' 'drugX' 'drugX' 'drugX' 'DrugY' 'drugB' 'DrugY' 'drugX' 'drugX'
 'drugX' 'drugA' 'drugC' 'DrugY' 'DrugY' 'DrugY' 'drugX' 'DrugY' 'DrugY'
 'drugB' 'drugC' 'drugB' 'DrugY' 'drugX' 'DrugY' 'DrugY' 'drugA' 'DrugY'
 'drugX' 'drugB' 'DrugY' 'drugA' 'drugX' 'DrugY' 'DrugY' 'drugB' 'DrugY'
 'drugX' 'DrugY' 'DrugY' 'DrugY' 'drugA' 'DrugY' 'drugA' 'drugX' 'drugB'
 'drugX' 'drugC' 'drugA' 'drugC' 'drugB' 'drugX' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'drugX' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'drugA' 'drugA' 'drugC' 'drugX' 'DrugY' 'drugX' 'drugX' 'DrugY'
 'drugB' 'DrugY' 'drugA' 'drugX' 'drugX' 'drugX' 'drugX' 'DrugY' 'drugX'
 'drugX' 'drugA' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'D

# Encoding Categorical Data


In [80]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

ct_X = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1, 2, 3])], remainder='passthrough')
X = np.array(ct_X.fit_transform(X))

le = LabelEncoder()
y = le.fit_transform(y)

In [81]:
# np.set_printoptions(threshold=np.inf)
print(X)
# print(X[:, -2:])

[[1.0 0.0 1.0 0.0 0.0 1.0 0.0 23 25.355]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 47 13.093]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 47 10.114]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 28 7.798]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 61 18.043]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 22 8.607]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 49 16.275]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 41 11.037]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 60 15.171]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 43 19.368]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 47 11.767]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 34 19.199]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 43 15.376]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 74 20.942]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 50 12.703]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 16 15.516]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 69 11.455]
 [0.0 1.0 1.0 0.0 0.0 1.0 0.0 43 13.972]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 23 7.298]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 32 25.974]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 57 19.128]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 63 25.917]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 47 30.568]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 48 15.036]
 [1.0 0.0 0.0 1.0 0

In [82]:
print(y)

[0 3 3 4 0 4 0 3 0 0 3 0 0 0 4 0 4 1 3 0 0 0 0 0 0 0 0 4 0 0 4 2 4 0 4 4 1
 4 4 4 0 2 0 4 4 4 1 3 0 0 0 4 0 0 2 3 2 0 4 0 0 1 0 4 2 0 1 4 0 0 2 0 4 0
 0 0 1 0 1 4 2 4 3 1 3 2 4 0 0 0 0 0 0 0 0 4 0 0 0 0 1 1 3 4 0 4 4 0 2 0 1
 4 4 4 4 0 4 4 1 0 0 0 0 0 2 0 0 4 0 4 0 0 4 0 0 4 2 1 2 4 1 0 2 0 1 4 4 1
 4 3 1 2 4 4 0 3 1 0 3 4 4 2 4 0 0 0 0 4 0 1 4 4 0 0 1 0 1 0 0 0 0 4 4 0 0
 0 2 1 0 0 0 1 0 3 0 3 3 4 4 4]


# Splitting the dataset into Training and Testing sets


In [83]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [84]:
print(X_train)

[[1.0 0.0 1.0 0.0 0.0 0.0 1.0 28 18.809]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 15 9.084]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 72 14.642]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 40 10.103]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 23 16.85]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 54 24.658]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 36 16.753]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 55 10.977]
 [0.0 1.0 1.0 0.0 0.0 0.0 1.0 65 34.997]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 32 7.477]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 37 16.724]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 69 10.065]
 [0.0 1.0 1.0 0.0 0.0 1.0 0.0 23 8.011]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 26 19.161]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 37 13.091]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 32 10.292]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 67 10.898]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 43 12.859]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 45 10.017]
 [0.0 1.0 1.0 0.0 0.0 0.0 1.0 31 17.069]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 50 12.703]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 49 13.598]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 55 7.261]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 39 13.938]
 [1.0 0.0 1.0 0.0 0.0

# Feature Scaling


In [85]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, -2:] = sc.fit_transform(X_train[:, -2:])
X_test[:, -2:] = sc.transform(X_test[:, -2:])

In [86]:

print(X_train)

[[1.0 0.0 1.0 0.0 0.0 0.0 1.0 -0.965126841550712 0.3815419315848126]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 -1.7430413019680266 -0.9636202220775643]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 1.6678144090925062 -0.19483757425694845]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 -0.2470519550116525 -0.8226721259765913]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 -1.2643247109419868 0.11057302063112666]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 0.5907020792839169 1.1905757040034493]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 -0.48641025052467235 0.0971559790984529]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.6505416531621719 -0.7017804321667284]
 [0.0 1.0 1.0 0.0 0.0 0.0 1.0 1.2489373919447215 2.6206663473674916]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 -0.7257685460376923 -1.1859004874693833]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 -0.4265706766464174 0.09314469864023092]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 1.4882956874577413 -0.8279282865770202]
 [0.0 1.0 1.0 0.0 0.0 1.0 0.0 -1.2643247109419868 -1.1120375990317783]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 -1.084805989307222 0.4302305771466796]
 [1.0 0.0 1.0 0.

# Fitting the model to the Training set

In [87]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(max_iter = 10000)
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

# Predicting the Test Set

In [88]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [4 4]
 [3 3]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [4 4]
 [4 4]
 [0 0]
 [0 0]
 [1 1]
 [2 2]
 [1 2]
 [3 3]
 [0 0]
 [4 4]
 [0 0]
 [4 4]
 [4 4]
 [0 0]
 [0 0]
 [1 1]
 [2 2]
 [0 0]
 [4 4]
 [4 4]
 [4 4]
 [0 0]
 [0 2]
 [4 4]
 [1 1]
 [4 4]
 [3 3]
 [2 2]
 [0 0]
 [4 4]
 [0 0]
 [0 1]
 [3 3]
 [2 2]
 [4 4]
 [0 0]
 [1 1]
 [0 0]
 [4 4]
 [0 0]
 [4 4]
 [4 4]
 [4 4]
 [3 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


# Evaluating the model

In [89]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[25  0  0  1  0]
 [ 1  6  0  0  0]
 [ 1  1  4  0  0]
 [ 0  0  0  4  0]
 [ 0  0  0  0 17]]


0.9333333333333333