# Import the modules

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Import the dataset

In [2]:
dataset = pd.read_csv("/content/drive/MyDrive/Machine Learning A - Z/Part 3 - Classification/Classification Summative Project/drug200.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Encoding the Categorical data

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

ct_X = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1, 2, 3])], remainder='passthrough')
X = np.array(ct_X.fit_transform(X))

le = LabelEncoder()
y = le.fit_transform(y)

# Splitting the dataset into Training and Test sets

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

# Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, -2:] = sc.fit_transform(X_train[:, -2:])
X_test[:, -2:] = sc.transform(X_test[:, -2:])

# Fit the Training set to the model

In [7]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

# Predicting the Test set

In [8]:
y_pred = classifier.predict(X_test)

# Evaluating the model

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 6  8  1  2  5]
 [ 0  9  3  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0  4  0]
 [ 0  0  0  0 17]]


0.6833333333333333