# Import the modules

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Import the dataset

In [9]:
dataset = pd.read_csv("/content/drive/MyDrive/Machine Learning A - Z/Part 3 - Classification/Classification Summative Project/drug200.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

# Encoding the categorical independent variables

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1, 2, 3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

le = LabelEncoder()
y = le.fit_transform(y)

# Splitting the dataset into Training and Test sets

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, -2:] = sc.fit_transform(X_train[:, -2:])
X_test[:, -2:] = sc.transform(X_test[:, -2:])

# Fit the model with the Training set

In [13]:
from sklearn.svm import SVC

classifier = SVC(kernel='linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

# Predict the Test set

In [14]:
y_pred = classifier.predict(X_test)

# Evaluate the model

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[26  0  2  0  3]
 [ 0  6  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0  4  0]
 [ 1  0  0  0 15]]


0.9